# Generated by Django 3.1 on 2020-08-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('tags', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming')], max_length=100)),
                ('thumbnail', models.ImageField(upload_to='upload/')),
                ('theme', models.TextField()),
                ('first_price', models.IntegerField()),
                ('second_price', models.IntegerField()),
                ('third_price', models.IntegerField()),
                ('eligibility', models.CharField(max_length=400)),
                ('entry_type', models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], max_length=2)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Copyright',
                'verbose_name_plural': 'Copyrights',
            },
        ),
        migrations.CreateModel(
            name='Judgecat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Judgecat',
                'verbose_name_plural': 'Judgecats',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.judgecat')),
            ],
            options={
                'verbose_name': 'Judge',
                'verbose_name_plural': 'Judges',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('gallery_image', models.ImageField(upload_to='upload/')),
                ('gallery_desc', models.TextField()),
                ('announced_date', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('first_place_image', models.ImageField(upload_to='upload/')),
                ('first_place_photo_id', models.IntegerField()),
                ('second_place_image', models.ImageField(upload_to='upload/')),
                ('second_place_photo_id', models.IntegerField()),
                ('third_place_image', models.ImageField(upload_to='upload/')),
                ('third_place_photo_id', models.IntegerField()),
                ('best_entry1_id', models.IntegerField(blank=True, null=True)),
                ('best_entry2_id', models.IntegerField(blank=True, null=True)),
                ('best_entry3_id', models.IntegerField(blank=True, null=True)),
                ('best_entry4_id', models.IntegerField(blank=True, null=True)),
                ('best_entry5_id', models.IntegerField(blank=True, null=True)),
                ('best_entry6_id', models.IntegerField(blank=True, null=True)),
                ('best_entry7_id', models.IntegerField(blank=True, null=True)),
                ('best_entry8_id', models.IntegerField(blank=True, null=True)),
                ('best_entry9_id', models.IntegerField(blank=True, null=True)),
                ('best_entry10_id', models.IntegerField(blank=True, null=True)),
                ('best_entry11_id', models.IntegerField(blank=True, null=True)),
                ('best_entry12_id', models.IntegerField(blank=True, null=True)),
                ('best_entry13_id', models.IntegerField(blank=True, null=True)),
                ('best_entry14_id', models.IntegerField(blank=True, null=True)),
                ('best_entry15_id', models.IntegerField(blank=True, null=True)),
                ('best_entry16_id', models.IntegerField(blank=True, null=True)),
                ('best_entry17_id', models.IntegerField(blank=True, null=True)),
                ('best_entry18_id', models.IntegerField(blank=True, null=True)),
                ('best_entry19_id', models.IntegerField(blank=True, null=True)),
                ('best_entry20_id', models.IntegerField(blank=True, null=True)),
                ('best_entry21_id', models.IntegerField(blank=True, null=True)),
                ('best_entry22_id', models.IntegerField(blank=True, null=True)),
                ('best_entry23_id', models.IntegerField(blank=True, null=True)),
                ('best_entry24_id', models.IntegerField(blank=True, null=True)),
                ('best_entry25_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('judges', models.ManyToManyField(to='core.Judge')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Contestimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='contest-image/')),
                ('image_title', models.CharField(max_length=340)),
                ('status', models.BooleanField(default=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Contestimg',
                'verbose_name_plural': 'Contestimgs',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='copyright',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.copyright'),
        ),
        migrations.AddField(
            model_name='contest',
            name='judges',
            field=models.ManyToManyField(to='core.Judge'),
        ),
    ]
