# Generated by Django 3.1 on 2020-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_activation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
