# Generated by Django 3.1 on 2020-08-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200818_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.judgecat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
