# Generated by Django 3.1 on 2020-08-18 10:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200818_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='judge',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
