# Generated by Django 3.1 on 2020-08-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200818_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='first_place_image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='second_place_image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='third_place_image',
        ),
    ]
